### PR TITLE
Walker: migrate to 2.0.0

### LINKED ISSUE #1871: Walker instance is not being killed on keybind
### System details

Intel(R) Core(TM) i7-8700K (12) @ 4.80 GHz, NVIDIA GeForce GTX 1070 Ti, Omarchy v3.0.1

### What's wrong?

When a walker menu is already open, press a shortcut that opens the same or other walker menu. The previous instance is not killed, so the previous items remain as new ones appear in the same picker.

https://github.com/user-attachments/assets/1f3666bc-27f3-4df0-9027-b6c201e09872

### LINKED ISSUE #1874: Preserving the history between walker navigation
### What do you need?

If a user wants to navigate through the Omarchy menu to find something they need, by pressing Escape they can go back, however the focused item in the new menu is not what they just used.

Take this scenario:
- user opens the Omarchy menu,
- user goes to Install,
- user didn't find what they needed, presses Escape,
- user lands back on the Omarchy menu,

Current behavior:
- **the focused item is Apps**

Proposed behavior:
- **the focused item is Install**

### PR DESCRIPTION
**Pull request by abenz1267**
I think i've setup everything needed, but since I don't run omarchy I can't fully confirm. So please test.

Fixes #1871
Fixes #1874

### CODE REVIEW

**Comment by ryanrhughes** [comment]
Sounds like a great reason to make the jump over to Omarchy @abenz1267. 😉

Thanks for doing this though. I'll pull this down and put it through some paces to see if I find anything.

**Comment by abenz1267** [comment]
i've actually removed the dmenu and keybindings themes. i don't think they are needed.

**Comment by dhh** [comment]
I just pulled this to give it a try. Maybe there's something wrong with the migration?

image

**Comment by abenz1267** [comment]
this looks you are still on walker 0.13.*

**Comment by dhh** [comment]
Yeah, I am. I get:

```
omarchy walkermigration * ❯ walker --version
Running Service: false
0.13.26
```

Ahh, I think it's because there's a rust conflict:

```
looking for conflicting packages...
:: rustup-1.28.2-3 and rust-1:1.89.0-1 are in conflict. Remove rust? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: rustup-1.28.2-3 and rust-1:1.89.0-1 are in conflict
 -> Failed to install layer, rolling up to next layer.error:error installing repo packages
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 chaotic-aur is up to date
resolving dependencies...
looking for conflicting packages...
:: rustup-1.28.2-3 and rust-1:1.89.0-1 are in conflict. Remove rust? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: rustup-1.28.2-3 and rust-1:1.89.0-1 are in conflict
 -> error installing repo packages
error installing repo packages
```

**Comment by dhh** [comment]
Removed rust, but we need a better solution for that, I think. Also seeing this when it's compiling:

image

**Comment by dhh** [comment]
Got it installed, but it fails to launch with:

image

**Comment by dhh** [comment]
Ran the migration again, and getting this:

image

**Comment by abenz1267** [comment]
fixed the theme thingy. also updated the aur package to use rust instead of rustup.

**Comment by dhh** [comment]
Style needs a bit of work to match what we had. This is how it looks out of the box. It's not tall enough (so there's scrolling), it's got a blinking cursor:

image

And it's got a flash when you jump between menus that wasn't there before either.

The dynamic Font menu isn't working. It's under Style > Font. Same with the dynamic theme menu.

**Comment by dhh** [comment]
Actually, I guess we always had a blinking cursor! What are missing is the "Go..." placeholder for typing. Here's what the current menu looks like:

image

**Comment by abenz1267** [comment]
fixed walker for the `-p` parameter... menu should be bigger now as well.

**Comment by dhh** [comment]
Thanks for working on this! As soon as AUR is back, I'll test more. Would make it a bit easier to review the diff if we could keep the indention (2 spaces) the same as it was (and same as rest of the project).

**Comment by abenz1267** [comment]
fixed it. i've also added `.editorconfig` files ...

File: bin/omarchy-menu [hunk 1]
```diff
@@ -3,124 +3,124 @@
...
 present_terminal() {
-  alacritty --class Omarchy -e bash -c "omarchy-show-logo; eval \"$1\"; omarchy-show-done;"
+    alacritty --class Omarchy -e bash -c "omarchy-show-logo; eval \"$1\"; omarchy-show-done;"
 }
 
 edit_in_nvim() {
-  notify-send "Editing config file" "$1"
-  alacritty -e nvim "$1"
+    notify-send "Editing config file" "$1"
+    alacritty -e nvim "$1"
```
Comment (dhh) [inline bin/omarchy-menu]: These are still extra indented.

Comment (abenz1267) [reply bin/omarchy-menu]: lies.

**Comment by jamesmcm** [comment]
@dhh for the Rust issue I think we can switch to install the rustup version of Rust? This is also what Rust developers would want anyway.

I think we just need to install `rustup` instead of `rust` and then initialise it with the stable toolchain: `rustup default stable` - this would then make it easy to install rust-analyzer, rustfmt, etc. for development, as in https://wiki.archlinux.org/title/Rust

(assuming walker doesn't require nightly)

**Comment by dhh** [comment]
Please do explore that change. Should run rust as rusticians would want it!

**Comment by abenz1267** [comment]
I think omarchy should install `rustup` instead of `rust`. But still the AUR package is broken. I will fix it. It shouldn't rely on rustup OR rust, but cargo.

**Comment by ahowardm** [comment]
@ryanrhughes to help you with indentation I made this PR: https://github.com/basecamp/omarchy/pull/1706

**Comment by dhh** [comment]
First thing I saw after migrating was this:

image

**Comment by dhh** [comment]
I fixed the migration to use `omarchy-refresh-walker`, to get the latest config, and that fixed it.

But the UI still isn't quite right. The not-found state expands the box weirdly sideways. The submenus have too much dead space beneath them. They need to be capped to just the length of the items.


https://github.com/user-attachments/assets/299c11c7-2a02-4067-bfa8-10cbc5802950

**Comment by dhh** [comment]
The highlight is also too pronounced. It should just be italic:

image

**Comment by dhh** [comment]
The app launcher isn't working out the box:

image

**Comment by abenz1267** [comment]
styling should be fixed.

**Comment by dhh** [comment]
I'm still seeing the oversized menus:

image

The menu is now better when it doesn't find results, but it now shrinks instead of supersizes. It needs to stay the same size and "No Results" should be up at the top like it was before:


https://github.com/user-attachments/assets/d69474cc-c2f3-4b45-a86b-d6ca84932cb5

**Comment by dhh** [comment]
The app launcher search also seems to be busted:

image

**Comment by dhh** [comment]
Actually, looks like it was always busted. It ought only to find complete words or word fragments:

**Comment by abenz1267** [comment]
Walker generally searches app titles, keywords and descriptions. And weights those. F.e.

image

The "problem" is that omarchy hides the subtext, so indeed a "why does it match?" might arise. But it always did that. I'd add an option to NOT search keywords/comment/description.

**Comment by dhh** [comment]
Just managed to get the opposite of too large of a box. Now it's too small. Not sure what triggered it:

image

**Comment by abenz1267** [comment]
i had to push a little rework in regards to how walker handles `-w/-h` flags, so update pls. also added the option for elephant to only search for titles and not categories/keywords/comments.

should be updated in the aur in a few minutes.

adjusted the styling to reflect the changes... let me know if it's correct now or still wonky.

**Comment by abenz1267** [comment]
image

you dont want the keybind hints at the bottom?

**Comment by dhh** [comment]
What are these keybind hints for? I personally prefer to have the whole thing as clean as possible. Would rather handle this in docs.

**Comment by abenz1267** [comment]
Displaying actions for whatever item is selected.

image

f.e. for the finder.

Personally i don't mind them at all and they are certainly helpful. IMO docs aren't the best place. Even i forgot f.e. how to edit a clipboard item.

**Comment by dhh** [comment]
I'll give them another look before Omarchy 3.1 👍

**Comment by joaomendoncaa** [comment]
Made the migration here and I'm noticing some layout shifting issues.


https://github.com/user-attachments/assets/bfc44926-2b50-409c-bd3c-6e5c5a1eb812

**Comment by joaomendoncaa** [comment]
Another small but noticeable QoL improvement would be having walker at a fixed distance from the top instead of always centered, this way the input wouldn't shift between searches.

https://github.com/user-attachments/assets/5bc16ac6-dff5-49ac-ad6d-a782176150e1

File: install/config/walker-elephant.sh [hunk 2]
```diff
@@ -0,0 +1,23 @@
+#!/bin/bash
+
+# Install elephant systemd service
+install -D -m 644 $OMARCHY_PATH/default/systemd/user/elephant.service ~/.config/systemd/user/elephant.service
```
Comment (melpomene) [inline install/config/walker-elephant.sh]: Should the service file `$OMARCHY_PATH/default/systemd/user/elephant.service` be included in the PR?

**Comment by dhh** [comment]
Just tried this again. The --width parameter is broken for me. Regardless of what it's set to, it seems to be stuck at like 600. I'm on Walker 1.0.8.

So I end up with menus lookling like this:

image

**Comment by abenz1267** [comment]
the `--width` parameter is taken for the whole box. But it will grow if the content inside the box is larger.

`--minwidth` and `--maxwidth` are for setting the size of the scrolled content.

**Comment by abenz1267** [comment]
I'll update this PR for the latest changes. You'll need to update walker/elephant afterwards.

**Comment by dhh** [comment]
Migration for this doesn't work:

```
omarchy walkermigration ❯ omarchy-migrate

Running migration (1758107878)
Migrate to Walker 1.0.0-Beta
[sudo] password for dhh:
checking dependencies...
:: imagemagick optionally requires openexr: OpenEXR support

Package (7)    Old Version  Net Change

cfitsio        1:4.6.3-1     -2.10 MiB
imath          3.2.1-1      -26.61 MiB
libcgif        0.5.0-1       -0.03 MiB
libimagequant  4.4.0-1       -0.61 MiB
libvips        8.17.2-1     -29.78 MiB
openexr        3.4.0-1       -4.67 MiB
walker-bin     0.13.26-1    -20.66 MiB

Total Removed Size:  84.45 MiB

:: Do you want to remove these packages? [Y/n]
:: Running pre-transaction hooks...
(1/1) Wait for limine-snapper-sync to finish before updating, installing or removing.
:: Processing package changes...
(1/7) removing walker-bin                                                                                                    [----------------------------------------------------------------------------] 100%
(2/7) removing libvips                                                                                                       [----------------------------------------------------------------------------] 100%
(3/7) removing openexr                                                                                                       [----------------------------------------------------------------------------] 100%
(4/7) removing imath                                                                                                         [----------------------------------------------------------------------------] 100%
(5/7) removing libimagequant                                                                                                 [----------------------------------------------------------------------------] 100%
(6/7) removing libcgif                                                                                                       [----------------------------------------------------------------------------] 100%
(7/7) removing cfitsio                                                                                                       [----------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
error: target not found: elephant-bluetooth
error: target not found: elephant-unicode
error: target not found: elephant-todo
install: cannot stat '/home/dhh/.local/share/omarchy/default/systemd/user/elephant.service': No such file or directory
Failed to enable unit: Unit elephant.service does not exist
rm: cannot remove '/home/dhh/.config/walker/themes': Is a directory
Replaced /home/dhh/.config/walker/config.toml with new Omarchy default.
Saved backup as /home/dhh/.config/walker/config.toml.bak.1759913526.

Changes:
1,42c1,54
< force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
< close_when_open = true                                                      # close walker when invoking while already opened
< selection_wrap = true                                                       # wrap list if at bottom or top
< click_to_close = true                                                       # closes walker if clicking outside of the main content area
< global_argument_delimiter = "#"                                             # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
< exact_search_prefix = "'"                                                   # disable fuzzy searching
< theme = "omarchy-default"                                                   # theme to use
< disable_mouse = false                                                       # disable mouse (on input and list only)
< additional_theme_location = "~/.local/share/omarchy/default/walker/themes/"
<
< [shell]
< anchor_top = true
< anchor_bottom = true
< anchor_left = true
< anchor_right = true
<
< [placeholders]
< "default" = { input = " Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"
<
< [keybinds]
< close = ["Escape"]
< next = ["Down"]
< previous = ["Up"]
< toggle_exact = ["ctrl e"]
< resume_last_query = ["ctrl r"]
< quick_activate = []
<
< [providers]
< default = [
<   "desktopapplications",
<   "menus",
<   "websearch",
< ] # providers to be queried by default
< empty = ["desktopapplications"] # providers to be queried when query is empty
<
< [[providers.prefixes]]
< prefix = "/"
< provider = "providerlist"
<
< [[providers.prefixes]]
< prefix = "."
< provider = "files"
---
> close_when_open = true
> theme = "omarchy-default"
> theme_base = []
> theme_location = ["~/.local/share/omarchy/default/walker/themes/"]
> hotreload_theme = true
> force_keyboard_focus = true
> timeout = 60
>
> [keys.ai]
> run_last_response = ["ctrl e"]
>
> [list]
> max_entries = 200
> cycle = true
>
> [search]
> placeholder = " Search..."
>
> [builtins.hyprland_keybinds]
> path = "~/.config/hypr/hyprland.conf"
> hidden = true
>
> [builtins.applications]
> launch_prefix = "uwsm app -- "
> placeholder = " Search..."
> prioritize_new = false
> context_aware = false
> show_sub_when_single = false
> history = false
> icon = ""
> hidden = true
>
> [builtins.applications.actions]
> enabled = false
> hide_category = true
>
> [builtins.bookmarks]
> hidden = true
>
> [[builtins.bookmarks.entries]]
> label = "Omarchy - Github"
> url = "https://github.com/basecamp/omarchy"
> keywords = ["omarchy", "github"]
>
> [[builtins.bookmarks.entries]]
> label = "Omarchy Manual"
> url = "https://manuals.omamix.org/2/the-omarchy-manual"
> keywords = ["omarchy"]
>
> [builtins.calc]
> name = "Calculator"
> icon = ""
> min_chars = 3
> prefix = "="
44c56,71
< [[providers.prefixes]]
---
> [builtins.windows]
> switcher_only = true
> hidden = true
>
> [builtins.clipboard]
> hidden = true
>
> [builtins.commands]
> hidden = true
>
> [builtins.custom_commands]
> hidden = true
>
> [builtins.emojis]
> name = "Emojis"
> icon = ""
46d72
< provider = "symbols"
48,50c74,97
< [[providers.prefixes]]
< prefix = "="
< provider = "calc"
---
> [builtins.symbols]
> after_copy = ""
> hidden = true
>
> [builtins.finder]
> use_fd = true
> cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
> icon = "file"
> name = "Finder"
> preview_images = true
> hidden = false
> prefix = "."
>
> [builtins.runner]
> shell_config = ""
> switcher_only = true
> hidden = true
>
> [builtins.ssh]
> hidden = true
>
> [builtins.websearch]
> switcher_only = true
> hidden = true
52,141c99,100
< [[providers.prefixes]]
< prefix = "@"
< provider = "websearch"
<
< [[providers.prefixes]]
< prefix = "$"
< provider = "clipboard"
<
< [providers.actions]
< dmenu = [{ action = "select", default = true, bind = "Return" }]
<
< providerlist = [
<   { action = "activate", default = true, bind = "Return", after = "ClearReload" },
< ]
<
< bluetooth = [
<   { action = "find", global = true, bind = "ctrl f", after = "AsyncClearReload" },
<   { action = "trust", bind = "ctrl t", after = "AsyncReload" },
<   { action = "untrust", bind = "ctrl t", after = "AsyncReload" },
<   { action = "pair", bind = "Return", after = "AsyncReload" },
<   { action = "remove", bind = "ctrl d", after = "AsyncReload" },
<   { action = "connect", bind = "Return", after = "AsyncReload" },
<   { action = "disconnect", bind = "Return", after = "AsyncReload" },
< ]
<
< archlinuxpkgs = [
<   { action = "install", bind = "Return", default = true },
<   { action = "remove", bind = "Return" },
< ]
<
< calc = [
<   { action = "copy", default = true, bind = "Return" },
<   { action = "delete", bind = "ctrl d", after = "AsyncReload" },
<   { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
< ]
<
< websearch = [
<   { action = "search", default = true, bind = "Return" },
<   { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
< ]
<
< desktopapplications = [
<   { action = "start", default = true, bind = "Return" },
<   { action = "start", label = "open+next", bind = "shift Return", after = "KeepOpen" },
<   { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
<   { action = "pin", bind = "ctrl p", after = "AsyncReload" },
<   { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
<   { action = "pinup", bind = "ctrl n", after = "AsyncReload" },
<   { action = "pindown", bind = "ctrl m", after = "AsyncReload" },
< ]
<
< files = [
<   { action = "open", default = true, bind = "Return" },
<   { action = "opendir", label = "open dir", bind = "ctrl Return" },
<   { action = "copypath", label = "copy path", bind = "ctrl shift c" },
<   { action = "copyfile", label = "copy file", bind = "ctrl c" },
< ]
<
< todo = [
<   { action = "save", default = true, bind = "Return", after = "ClearReload" },
<   { action = "delete", bind = "ctrl d", after = "ClearReload" },
<   { action = "active", bind = "Return", after = "ClearReload" },
<   { action = "inactive", bind = "Return", after = "ClearReload" },
<   { action = "done", bind = "ctrl f", after = "ClearReload" },
<   { action = "clear", bind = "ctrl x", after = "ClearReload", global = true },
< ]
<
< runner = [
<   { action = "run", default = true, bind = "Return" },
<   { action = "runterminal", label = "run in terminal", bind = "shift Return" },
<   { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
< ]
<
< symbols = [
<   { action = "run_cmd", label = "select", default = true, bind = "Return" },
<   { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
< ]
<
< unicode = [
<   { action = "run_cmd", label = "select", default = true, bind = "Return" },
<   { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload" },
< ]
<
< clipboard = [
<   { action = "copy", default = true, bind = "Return" },
<   { action = "remove", bind = "ctrl d", after = "ClearReload" },
<   { action = "remove_all", global = true, label = "clear", bind = "ctrl shift d", after = "ClearReload" },
<   { action = "toggle_images", global = true, label = "toggle images", bind = "ctrl i", after = "ClearReload" },
<   { action = "edit", bind = "ctrl o" },
< ]
---
> [builtins.translation]
> hidden = true

omarchy walkermigration ❯ Command not found: "elephant"
Command not found: "walker"
```

**Comment by dhh** [comment]
We got there!! Everything is working 👌

File: bin/omarchy-launch-walker [hunk 3]
```diff
@@ -0,0 +1,8 @@
+#!/bin/bash
+
+# Ensure elephant is running before launching walker
+if ! pgrep -x elephant > /dev/null; then
+  setsid uwsm app -- elephant &
```
Comment (woopstar) [inline bin/omarchy-launch-walker:5]: This should use uswm-app for performance

File: bin/omarchy-restart-walker [hunk 4]
```diff
@@ -1,7 +1,6 @@
 #!/bin/bash
 
+pkill elephant
+setsid uwsm app -- elephant &
```
Comment (woopstar) [inline bin/omarchy-restart-walker:4]: should use uwsm-app

File: bin/omarchy-launch-walker (hunk 3 above)
Comment (abenz1267) [reply bin/omarchy-launch-walker:5]: this is more of a paranoia-code anyways. it shouldnt even be there. elephant should just be run as a service with restart on failure.

File: bin/omarchy-restart-walker (hunk 4 above)
Comment (abenz1267) [reply bin/omarchy-restart-walker:4]: doesnt really matter. this isnt performance critical code and 100ms or 50ms doesnt make a difference here.
